version: "3.8"

services:
  db:
    image: postgres
    container_name: pgtest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5

  app:
    build: ./app
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./users.csv:/app/users.csv:ro
